### ISSUE TITLE
VD PinWindow function doesn't work with ahk_id

### ISSUE THREAD

**Issue by megamorphg** [FuPeiJiang/VD.ahk#17]
As per a [Stack Overflow answer](https://superuser.com/a/1733163/245425):
I tried using process ID but I think VD.PinWindow doesn't work with it e.g. VD.PinWindow("ahk_id 0xD3854") or VD.PinWindow("ahk_id %this_id%").

Full code used:
```
#Persistent
; If the script is not elevated, relaunch as administrator and kill current instance
full_command_line := DllCall("GetCommandLine", "str")

if not (A_IsAdmin or RegExMatch(full_command_line, " /restart(?!\S)"))
{
    try ; leads to having the script re-launching itself as administrator
    {
        if A_IsCompiled
            Run *RunAs "%A_ScriptFullPath%" /restart
        else
            Run *RunAs "%A_AhkPath%" /restart "%A_ScriptFullPath%"
    }
    ExitApp
}

#Include lib\VD.ahk-class_VD\_VD.ahk

WinGet, HWiNFO64List, List, ahk_exe HWiNFO64.EXE
VD.init()

Loop, %HWiNFO64List%
{
	this_id := HWiNFO64List%A_Index%
	VD.PinWindow("%this_id%")
	; MsgBox %this_id%
}
```

**Comment by FuPeiJiang** [comment]
try
`VD.PinWindow("ahk_id " this_id)`
instead of
`VD.PinWindow("%this_id%")`

this is a scripting error
`%` is not to be used inside quotes
___
`this_id` is a variable
this is how you'd write it in javascript: string concatenation
`VD.PinWindow("ahk_id " + this_id)`
this is how you'd write it in ahk: `.` is string concatenation operator
`VD.PinWindow("ahk_id " . this_id)`
or (concatenation is assumed):
`VD.PinWindow("ahk_id " this_id)`
___
props to you for putting Full code
___
you can also 'step into' using a debugger and see that the parameter's value isn't what you want
I use <https://marketplace.visualstudio.com/items?itemName=zero-plusplus.vscode-autohotkey-debug#installation>

**Comment by megamorphg** [comment]
Thank you! That worked. The parameter is already variabilized so it was failing.

```
      WinGet, HWiNFO64List, List, ahk_exe HWiNFO64.EXE
      Loop, %HWiNFO64List%
      {
         this_id := HWiNFO64List%A_Index%
         VD.PinWindow("ahk_id " this_id)
      }
```
