### ISSUE TITLE
Don't work on windows 11(21h2)!

### ISSUE THREAD

**Issue by ruhchjdbdbhccjjc** [FuPeiJiang/VD.ahk#2]
Hi! I use this ahk that made by you(Nice AHK)! But yesterday,when I update to windows 11,it break!
Almost script don't work anymore!
DO you have time to fix it?

**Comment by FuPeiJiang** [comment]
which functions don't work ?
___
these are DllCall to WinAPI undocumented functions (virtual desktop), they probably got removed in windows 11 ?
I thought windows was all about backward compatibility, I'll have to look
but I don't have windows 11, and I don't want to get it. Convince me. why should I update to windows 11?
___
win11 has new virtual desktop features, new winapi documentation will come out soon probably
there is no windows 11 sdk download yet
___
thank you, I won't update to windows 11 now because it will break my AHK

**Comment by ruhchjdbdbhccjjc** [comment]
Thank your reply anyway ! Have nice day !

**Comment by ruhchjdbdbhccjjc** [comment]
Thank you !

**Comment by FuPeiJiang** [comment]
@ruhchjdbdbhccjjc I could finally do this since I just got Windows 11 myself, and no time
the syntax has changed: it's a class now, instead of global functions
eg: `VD.goToDesktopNum()` instead of `VD_goToDesktopNum()`
Default branch is now `class_VD`

test it?

let me mark this: 289439c5b19d6260ec23fe78387c58ea0f12e2a5

**Comment by ruhchjdbdbhccjjc** [comment]
Thank you very much!
